### PR TITLE
[Chore] Bump Version number in current working files

### PR DESCRIPTION
**Pull request by mkhraisha**
this addresses: #212  and is a small housekeeping PR

### CODE REVIEW

**Review by OR13 — APPROVED** [review]

**Comment by OR13** [comment]
ping @msporny @peacekeeper

**Review by msporny — APPROVED** [review]

**Comment by msporny** [comment]
You may have to re-run this PR if we decide to pull these in: https://lists.w3.org/Archives/Public/public-credentials/2021Jul/0150.html ... just a heads up -- we can export as a patch to the new repo history or something similar.

**Comment by OR13** [comment]
@msporny I am merging this, we can handle patching later, PRs with approvals should get priority.

**Comment by msporny** [comment]
> @msporny I am merging this, we can handle patching later, PRs with approvals should get priority.

Ok, we'll just need to remember to cherry pick this commit if the group adopts the new split repo.

**Pull request merged**
