### PR TITLE
Plugfest 2021 release

### PR DESCRIPTION
**Pull request by mkhraisha**
This PR does a few things:

* locks in v0.0.2 of the API in hte same vein as previous versions.
* adds a new package -- plugfest-2021, which is a clone of the current vc-http-api-test-server
* adds a new command to package.json --  test:2021

once this is approved I can release to this commit

### CODE REVIEW

**Comment by mkhraisha** [comment]
Theres been a few updates to config since i isseud this PR. ill update this PR tmrw, and we can then hopefully cut the release.

**Comment by mavarley** [comment]
Thanks @mkhraisha - SK has a config change to support the revocationList2020 and bbs+ test cases #167 . No material changes, just config.

**Comment by tplooker** [comment]
@mkhraisha id prefer we not create another package and instead use GH tags to point to plugfest-2021

**Comment by mkhraisha** [comment]
@tplooker i generally agree but i was following the previous precedent of plugfest2020

**Comment by tplooker** [comment]
@mkhraisha yeap understand, however see #162 as i think we should remove plugfest-2020

**Comment by mkhraisha** [comment]
pending merge of the #167

**Review by OR13 — APPROVED** [review]

**Comment by mkhraisha** [comment]
Please review/merge this PR in before other PRs so we can keep a record of what exactly was tested on the plugfest.
@msporny @peacekeeper

**Review by msporny — APPROVED** [review]

**Pull request merged**
