### PR TITLE
begin to improve user experience around documentation

### PR DESCRIPTION
**Pull request by mprorock**
See issue #96

### CODE REVIEW

**Review by OR13 — CHANGES_REQUESTED** [review]
This change would break github pages hosting.

Suggest picking one of these files be index.html

**Comment by mprorock** [comment]
as redoc handles the full open api spec better (including optional parameters I am going to go with that

**Review by OR13 — APPROVED** [review]
I am ok switching from swagger rendering to redoc, as long as folks understand that the yaml / json is still the source of truth.

**Review by peacekeeper — APPROVED** [review]
Wonderful, looks like a great improvement! I agree YAML should be the source of truth and I think everyone understands that.

**Comment by mprorock** [comment]
> Wonderful, looks like a great improvement! I agree YAML should be the source of truth and I think everyone understands that.

yes.  I have also added a statement to that effect in the readme in PR #102 as this "should" be clear, but sometimes better to err on the side of verbosity, especially if you have someone like me reading the docs

**Review by msporny — APPROVED** [review]
+1 to moving to anything that makes our collective lives easier. I'm taking it on blind faith that redoc is better, haven't had a chance to review. I expect we'll move back to Swagger if people hate the move to redoc.

**Comment by mprorock** [comment]
@msporny agreed - it is also not an either or long term - we just have to ultimately figure out a clean way of handling the option with gh pages - key thing is making sure that the docs are readable and clear

**Comment by mprorock** [comment]
@msporny @peacekeeper @OR13 since this is fully approved and has no conflicts, can we merge this so that we can begin to build on top of it for better docs leading into the plugfest?

**Comment by msporny** [comment]
> @msporny @peacekeeper @OR13 since this is fully approved and has no conflicts, can we merge this so that we can begin to build on top of it for better docs leading into the plugfest?

I'm fine to merge, but don't know what the process is for this repo this time around. We used to give this 7 days or approval by people on interop calls, whichever happens sooner.

**Review by OR13 — APPROVED** [review]

**Comment by OR13** [comment]
> > @msporny @peacekeeper @OR13 since this is fully approved and has no conflicts, can we merge this so that we can begin to build on top of it for better docs leading into the plugfest?
> 
> I'm fine to merge, but don't know what the process is for this repo this time around. We used to give this 7 days or approval by people on interop calls, whichever happens sooner.
> 
> I almost hit the rebase and merge button and then thought "Doesn't look like much of the cohort is participating in the discussion, I'm sure someone might object if I hit `rebase and merge`".
> 
> PS: Everyone really needs to have better commit comment hygene, btw -- No merge commits, active voice, 50 characters, full sentences w/ capitalization, etc.)

I find that unless you have software that enforces this... or reviews that reject commits that are not nice... asking for this tends not to work.

I tend to prefer https://github.com/conventional-changelog/commitlint

**Comment by OR13** [comment]
regarding merging, lets wait 7 days... we will only ever be as fast as our slowest reviewers... we have historically given them 1 week to review things.

**Comment by OR13** [comment]
More incentive to get your PRs in ASAP : p

**Comment by mprorock** [comment]
> More incentive to get your PRs in ASAP : p

lol, totally get it.  in this case however, we likely need to build several PRs on top of this and #102 as a base set of PRs so that we can accurately separate concerns and make review easier on each PR, and actually be building off of something.  This PR is critical for the ability to accurately show details on parameters into the APIs at the documentation level, particularly with endpoints utilizing oneOf, allOf, etc.  The merge pace on this particular PR is less important than the raw docs PR #102 as a building block.

**Review by mkhraisha — APPROVED** [review]

**Comment by OR13** [comment]
Open for 7 days, not objections, merging.

**Pull request merged**
